### PR TITLE
Add Droidcon UK 2015 talk

### PR DESCRIPTION
**Pull request by AndrewJack**
Added my [talk](https://skillsmatter.com/skillscasts/6671-build-your-own-video-streaming-app) from droidcon.

### CODE REVIEW

**Comment by AndrewJack** [comment]
I've updated the PR to use the new format. The video isn't on youtube & private so the pop up page doesn't work. Can the link just point to an external site?

**Comment by tcrands** [comment]
Looks good. Can you just say in the description something like "Video can be found in link". Can you also put an image in the video field in raw HTML (<img src= etc...) and use this inline style (style='width:100%;height:515px'). This is because its rendered in the iframe that the youtube video would normally be.

**Comment by AndrewJack** [comment]
Video can be found link - done 

I have added the image to the iframe, however it doesn't look great. on a large screen the box is stretched.
I have added it to a separate html file, the raw html didn't work in the video field.

Any suggestions for making this a bit better?
Feel free to copy this branch and change it to suit your needs.

**Comment by craggy2593** [comment]
Checking out the branch, it doesn't look too bad to us, and the image doesn't appear stretched to us.

The raw HTML probably didn't work as that functionality might be work we have in an open pull requests ourselves. 

I'd be happy to see it go live, but thats down to you, if youre not happy, we can look more into it. (We will still look at possible solutions regardless)

**Comment by AndrewJack** [comment]
Happy for it to be merged, if you plan on improving it anyway.

**Pull request merged**
