### PR TITLE
Changes to go live

### PR DESCRIPTION
**Pull request by behaghel**
PR #67 rebased.

### CODE REVIEW

**Comment by behaghel** [comment]
@JuwonTiwo can you check that your work is still there? It's supposed to be a mere rebase on master.

**Comment by craggy2593** [comment]
@behaghel Can you clarify what you mean? From what I can see, the work that was in #67 is also in this PR, and the work in #67 has not been merged into master. 

To also answer your question on that PR, we originally removed the links from the meet up pages as we thought they went to the wrong places (we assumed they went to the specific event page, rather than the general page), and we felt that it was slightly misleading being directed to a general page rather than the specific event. On looking again, its clear this was never the case.

**Comment by behaghel** [comment]
I have just tried to be helpful here by doing the rebase required to be able to merge this work.

So are we saying those links where actually useful and then should be restored?

**Comment by craggy2593** [comment]
Sorry, my misunderstanding. I thought you were saying that the work was lost.

Yes, I guess so. How best do you suggest restoring them? As this is now off your fork, you can reject the merge and we will create a new pull request with only the remaining changes, or we can make a pull request after merge restoring the meetup links (we have the old copy, so will simply restore)?

**Comment by behaghel** [comment]
@craggy2593 `git checkout "HEAD^" -- meetups.html && git push` was my friend. Could you double check and merge if happy?

**Comment by craggy2593** [comment]
@behaghel: I don't have write access to be able to merge pull requests, but I can now see that the meetups changes have gone from the PR, with only the Sky Logo changing, and the Work for Us page being removed. I'd therefore be happy for it to merge.

(Also, thanks for that git statement, will definitely come in handy in future)

**Comment by behaghel** [comment]
thanks for your feedback @craggy2593, let me be your hands (though I totally think you should be granted access, happy to dig into this with you).

**Pull request merged**
